version: "3"

services:
  db:
    image: constellation-db
    deploy:
      replicas: 1
      resources:
        cpus: 0.1
        memory: 100M
    volumes:
      - ./dynamo/data:/opt/dynamodb/data
    ports:
      - "8000:8000"